FROM python:3.12-slim

WORKDIR /app/backend

COPY requirements.txt /app/backend/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/backend

ENV PYTHONPATH=/app

EXPOSE 8000 2024

CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
