apiVersion: v1
kind: Namespace
metadata:
  name: security-demo
---
apiVersion: v1
kind: Secret
metadata:
  name: demo-db-credentials
  namespace: security-demo
type: Opaque
stringData:
  username: demo-user
  password: demo-not-a-real-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-app
  namespace: security-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: privileged-demo
  namespace: security-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: privileged-demo
  template:
    metadata:
      labels:
        app: privileged-demo
    spec:
      serviceAccountName: demo-app
      containers:
        - name: app
          image: nginx:1.27-alpine
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            runAsUser: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostpath-demo
  namespace: security-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hostpath-demo
  template:
    metadata:
      labels:
        app: hostpath-demo
    spec:
      containers:
        - name: app
          image: nginx:1.27-alpine
          volumeMounts:
            - name: host-logs
              mountPath: /host-logs
              readOnly: true
      volumes:
        - name: host-logs
          hostPath:
            path: /var/log
            type: Directory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostnetwork-demo
  namespace: security-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hostnetwork-demo
  template:
    metadata:
      labels:
        app: hostnetwork-demo
    spec:
      hostNetwork: true
      containers:
        - name: app
          image: nginx:1.27-alpine
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weak-identity-demo
  namespace: security-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weak-identity-demo
  template:
    metadata:
      labels:
        app: weak-identity-demo
    spec:
      containers:
        - name: app
          image: nginx:1.27-alpine
          securityContext:
            allowPrivilegeEscalation: true
---
apiVersion: v1
kind: Service
metadata:
  name: external-demo
  namespace: security-demo
spec:
  type: NodePort
  selector:
    app: privileged-demo
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
